# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170725_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
    ]
