# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170725_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Exam')),
                ('subject', models.CharField(max_length=256, verbose_name='Exam')),
                ('teacher', models.CharField(max_length=256, verbose_name='Exam')),
                ('mark', models.CharField(max_length=3, verbose_name='\u041e\u0446\u0456\u043d\u043a\u0430')),
                ('notes', models.TextField(blank=True, verbose_name='\u0414\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u043d\u043e\u0442\u0430\u0442\u043a\u0438')),
                ('student', models.OneToOneField(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'verbose_name': '\u041e\u0446\u0456\u043d\u043a\u0430',
                'verbose_name_plural': '\u041e\u0446\u0456\u043d\u043a\u0438',
            },
        ),
    ]
