# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.CharField(max_length=256, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447'),
        ),
    ]
