# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170727_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442', 'verbose_name_plural': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442\u0438'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_time',
            field=models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430, \u0447\u0430\u0441'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.CharField(max_length=4, verbose_name='\u0411\u0456\u043b\u0435\u0442'),
        ),
    ]
