# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_monthjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day1',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21161'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day10',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211610'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day11',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211611'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day12',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211612'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day13',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211613'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day14',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211614'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day15',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211615'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day16',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211616'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day17',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211617'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day18',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211618'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day19',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211619'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day2',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21162'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day20',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211620'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day21',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211621'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day22',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211622'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day23',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211623'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day24',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211624'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day25',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211625'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day26',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211626'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day27',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211627'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day28',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211628'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day29',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211629'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day3',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21163'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day30',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211630'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day31',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u211631'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day4',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21164'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day5',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21165'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day6',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21166'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day7',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21167'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day8',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21168'),
        ),
        migrations.AlterField(
            model_name='monthjournal',
            name='present_day9',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u043d\u044c \u21169'),
        ),
    ]
