# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170912_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['group'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['student'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
